# Generated by Django 5.0.6 on 2024-06-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumni_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
