# Generated by Django 5.0.6 on 2024-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0002_question_user_avatar_user_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='user',
            name='over_image',
            field=models.ImageField(null=True, upload_to='social/%Y/%m/%d/', verbose_name='Pick overImage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='social/%Y/%m/%d/', verbose_name='Pick avatar'),
        ),
    ]
