# Generated by Django 5.0.6 on 2024-05-24 13:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0003_remove_user_cover_image_user_over_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='over_image',
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
