# Generated by Django 5.0.6 on 2024-05-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0004_remove_user_over_image_user_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='shared_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_post',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='shared_post',
        ),
    ]
