# Generated by Django 5.0.6 on 2024-05-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0005_remove_invitation_shared_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
